name: Deploy Gap Analyzer AI Agent

on:
  push:
    branches:
      - main
    paths:
      - 'AI-Agents/gap-analyzer'
      - 'AI-Agents/gap-analyzer/**'
      - '.github/workflows/deploy-gap-analyzer.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure service folder exists on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
            "mkdir -p /opt/scholarai/AI-Agents/gap-analyzer"

      - name: Copy gap-analyzer (incl. hidden files) to VM
        run: |
          scp -o StrictHostKeyChecking=no -r AI-Agents/gap-analyzer/. \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/opt/scholarai/AI-Agents/gap-analyzer/

      - name: Deploy Gap Analyzer AI Agent
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e

            echo "🚀 Starting Gap Analyzer AI Agent deployment..."
            cd /opt/scholarai/AI-Agents/gap-analyzer

            echo "🧹 Cleaning up old containers/images..."
            docker rm -f scholar-gap-analyzer || true
            docker image prune -f --filter "label=service=gap-analyzer" || true

            echo "🔑 Fixing directory ownership for container user (uid=100, gid=101)..."
            sudo mkdir -p ./logs ./paper ./cache ./uploads
            sudo chown -R 100:101 ./logs ./paper ./cache ./uploads

            echo "🔨 Building Gap Analyzer AI Agent..."
            if ! docker compose -f docker-compose.prod.yml build gap-analyzer; then
              echo "❌ Build failed, aborting deployment!"
              exit 1
            fi

            echo "📦 Starting Gap Analyzer AI Agent..."
            docker compose -f docker-compose.prod.yml up -d gap-analyzer

            echo "⏳ Waiting for Gap Analyzer AI Agent health..."
            healthy=0
            for i in {1..20}; do
              STATUS=$(docker inspect --format='{{json .State.Health.Status}}' scholar-gap-analyzer 2>/dev/null | tr -d '"')
              if [ "$STATUS" = "healthy" ]; then
                echo "✅ Gap Analyzer AI Agent is healthy!"
                echo "🌐 Access it at: http://${{ secrets.VM_HOST }}:8003"
                healthy=1
                break
              else
                echo "Still waiting... ($i/20)"
                sleep 10
              fi
            done

            if [ $healthy -eq 0 ]; then
              echo "❌ Gap Analyzer AI Agent failed to become healthy!"
              docker logs scholar-gap-analyzer || true
              exit 1
            fi

            echo "📊 Current Gap Analyzer AI Agent status:"
            docker ps --filter "name=scholar-gap-analyzer"
          EOF
